import React from 'react'
import './testimonials.css'
import AVTR1 from '../../assets/avatar1.jpg'
import AVTR2 from '../../assets/avatar2.jpg'



const data = [
  {
    avatar:AVTR1,
    name:'Senior Lecture:Hansi De Silva',
    review:'Many thanks for all your supporting statements and individual judgement towards my professional practices. I always receive many good-will statements year in year out, but I never thought of having it as an acknowledgement of all your appreciations. This idea has been generated by one of my children who asked me ‘What really makes you a good Lecturer or Professor?’ My answer was ‘a good Lecturer or Professor must be able to impact knowledge to others and contribute to knowledge within his or her research area’. My son replied, ‘not always the case, you should have a page on your website that shows realistic comments from your present and past students’. Now I have done exactly what my son said but if your comment does not appear among those listed below, please do not be offended, your comment might be among the 1 million still in my archive. Thanks for remembering to email me what you think, I wish you all the ‘Best of Luck’.'

  },

  {
    avatar:AVTR2,
    name:'Senior Lecture:dasun pathirana',
    review:'Many thanks for all your supporting statements and individual judgement towards my professional practices. I always receive many good-will statements year in year out, but I never thought of having it as an acknowledgement of all your appreciations. This idea has been generated by one of my children who asked me ‘What really makes you a good Lecturer or Professor?’ My answer was ‘a good Lecturer or Professor must be able to impact knowledge to others and contribute to knowledge within his or her research area’. My son replied, ‘not always the case, you should have a page on your website that shows realistic comments from your present and past students’. Now I have done exactly what my son said but if your comment does not appear among those listed below, please do not be offended, your comment might be among the 1 million still in my archive. Thanks for remembering to email me what you think, I wish you all the ‘Best of Luck’.'

  }
]


const Testimonials = () => {
  return (
    <section id='testimonials'>
      <h5>Review From Clients</h5>
      <h2>Testimonials</h2>

      <div className="container testimonials__container">
      {
          data.map(({avatar, name, review},index) => {
            return(
              <article key={index} className="testimonials">
          <div className="client__avatar">
            <img src={avatar} />
          </div>

            <h5 className='client_name'>{name}</h5>
              <small className='client__review'>
                  {review}
              </small>
          
        </article>
            )

          })
        }

      </div>
    </section>
  )
}

export default Testimonials